apiVersion: v1
kind: Service
metadata:
  name: {{ include "devops-app.fullname" . }}
spec:
  selector:
    app: {{ include "devops-app.name" . }}
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
